# Generated by Django 5.0.14 on 2026-05-31 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TuringMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('mt_file', models.FileField(upload_to='turing_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_string', models.CharField(blank=True, max_length=255)),
                ('final_tape', models.TextField()),
                ('status', models.CharField(choices=[('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada'), ('No Termina', 'No Termina (Límite de pasos superado)')], max_length=20)),
                ('steps_count', models.IntegerField(default=0)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('turing_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='turing_machine.turingmachine')),
            ],
        ),
    ]
